% 
% Loads a list of one-sample histograms, given a path and filenames as
% generated by command 'dir' (field .name)
%
% cf nyuAnnCollHst.m
%
function S = LoadFocHistList(pth, aFinas, NLEVARH)

nFinas  = length(aFinas);
fprintf('%4d instances', nFinas);

S.HST   = [];
S.Nlev  = zeros(nFinas,1,'uint8');

if nFinas==0                      % no features
    S.nInst = 0;
    S.KtLab = [];
    S.ntLev = 0;
    return;
end
    
for i = 1:nFinas
    
    fina1 = [pth aFinas(i).name];
    
    [HFU HFB Nunf Nbif Floc] = LoadFocHist(fina1);
    
    S.Nlev(i)   = Floc.nLev;
    
    [H1 len]    = u_HistCatFlat( HFU, HFB, Nunf, Nbif, Floc );

    if i==1
        S.HST = zeros( nFinas, len.tot, 'single' );
    end
    
    S.HST(i,:) = H1;

    if mod(i,50)==0, fprintf('.'); end
end

S.KtLab = histcounts(S.Nlev, 'BinLimits', [1 8]);
S.nInst = nFinas;
S.ntLev = max(S.Nlev);

minLev  = min(S.Nlev);
fprintf('\n\tnLevs: %d-%d: ', minLev, S.ntLev);
for l = 1:S.ntLev
    fprintf('%4d ', S.KtLab(l));
end
fprintf('\n');

assert(all(minLev>0));             % all must have at least 1 level
assert(all(S.ntLev<=NLEVARH));     % larger mxnLev should not occur

end

